### ISSUE TITLE
LPE vs. diff

### ISSUE THREAD

**Issue by ziqing97** [ziqing97/1.MasterSemester-SatGeoUebung#3]
Hi Nadine,

danke für die Entwicklung und die Ausarbeitung (du hast tatsächlich alles gemacht...)

Die Ausschläge finde ich nicht schwer zu erklären: für GOCE, zum Beispiel, haben wir 8 Perioden gerechnet. Die Anzahl der grossesten Ausschläge sind exakt 8. Wenn du x-Achse nach Anzahl der Perioden umsetzst, siehst du deutlicher. (die Ausschläge am Anfang und am Ende sind eine)
![edot](https://user-images.githubusercontent.com/64216101/99728226-68c52900-2ab9-11eb-8f93-a2f3c737e674.png)
 
Das heißt, solche Änderungen werden dokumentiert wenn du mit *diff* rechnest, die aber von LPE irgendwie ignoriet werden. (tiefere Gründe sollen noch diskuttiert werden denn für Aerobraking sehen a-dot und e-dot perfekt aus )
![e](https://user-images.githubusercontent.com/64216101/99729115-c017c900-2aba-11eb-847b-9952d7141c19.png)

verbleibendes Probleme sind a-dot von GOCE und w-dot + M-dot von Aerobraking. 2 Kurve da passen zueinander nicht.  (besondes bei a dot von GOCE)
![adot](https://user-images.githubusercontent.com/64216101/99729528-56e48580-2abb-11eb-9ae6-dc3b2bcaf908.png)

LG, Ziqing

**Comment by ziqing97** [comment]
Code sind in meine Test Funktion

**Comment by ziqing97** [comment]
btw, tdiff ist kein Konstant. Ich have dafür einen Vektor gebaut.

**Comment by ziqing97** [comment]
Ich habe ein paar andere Idee, können wir morgen dafür besprechen?

**Comment by siv825** [comment]
Ich habe mir mal das a  von GOCE angeschaut, dass mit cart2kep berechnet wurde. Zieht man von dem a den Radius, dann erhält man eine Höhe von 225 km bis 224.6935 km. Also irgendwie ist die Höhe von GOCE nicht konstant

**Comment by ziqing97** [comment]
> Ich habe mir mal das a von GOCE angeschaut, dass mit cart2kep berechnet wurde. Zieht man von dem a den Radius, dann erhält man eine Höhe von 225 km bis 224.6935 km. Also irgendwie ist die Höhe von GOCE nicht konstant

Stimmt, wegen Reibungskraft ist die Energie der Satellite niedriger -> Schwindigkeit kleiner -> Höhe kleiner.

**Comment by ziqing97** [comment]
Aber die Formel für Reibungskraft muss nicht geändert werden weil diese Höhenunterschiede so klein ist.

**Comment by siv825** [comment]
Könnte dies der Grund für die starke Abweichung von aPunkt von Kepler zu LPE sein? Bei LPE wird ja die Kraft berücksichtig, aber bei der Funktion cart2kep ja nicht?

> 
> 
> Aber die Formel für Reibungskraft muss nicht geändert werden weil diese Höhenunterschiede so klein ist.

**Comment by siv825** [comment]
> 
> 
> Könnte dies der Grund für die starke Abweichung von aPunkt von Kepler zu LPE sein? Bei LPE wird ja die Kraft berücksichtig, aber bei der Funktion cart2kep ja nicht?
> 
> > Aber die Formel für Reibungskraft muss nicht geändert werden weil diese Höhenunterschiede so klein ist.

Aber dann würde ja des bei Aerodrop auch nicht passen. Meine Idee macht kein Sinn mehr ...

**Comment by siv825** [comment]
Schreibe deine Anmerkungen von ganz oben, also zu den Graphen zu denen es passt in die Diskussion in die Ausarbeitung

**Comment by ziqing97** [comment]
Em, Nadine, ich denk wir haben falsche Formeln genutzt......

**Comment by siv825** [comment]
> 
> 
> Em, Nadine, ich denk wir haben falsche Formeln genutzt......

Wie das? In der Powerpoint für die Übung 1 hat er diese Formel gezeigt. Er hat zwar im Mittwoch in seinem Code andere benutz. Aber ich würde mich nicht an seinem Code orientieren sondern an der Powerpoint
